export const URLS = {
  myFlixReactLive: "https://fredpasqua.github.io/myflix-v2/#/",
  angularLink: "https://github.com/fredpasqua/myFlix-Angular-client",
  angularLive: "https://fredpasqua.github.io/myFlix-Angular-client/welcome",
  pokeLink: "https://github.com/fredpasqua/Pokedex-js-app",
  pokeLive: "https://fredpasqua.github.io/Pokedex-js-app/",
  meetLink: "https://github.com/fredpasqua/meet",
  meetLive: "https://fredpasqua.github.io/meet/",
  spellingLink: "https://github.com/fredpasqua/Spelling-Test-2",
  spellingLive: "https://fredsjams.com/spellinggame/index.html",
  apiLive: "https://github.com/fredpasqua/movie_api/blob/master/README.md",
  apiLink: "https://github.com/fredpasqua/movie_api",
  robotsLive: "https://fredpasqua.github.io/test/",
  robotsLink: "https://github.com/fredpasqua/test/tree/Company-Directory",
  horntraxLink: "https://github.com/fredpasqua/horntrax_v2.0",
  horntraxLive: "https://fredpasqua.github.io/horntrax_v2.0/",
  myFlixReactLink: "https://github.com/fredpasqua/myflix-v2",
  fredsJamsLink: "https://github.com/fredpasqua/fredsjams_client_v2/",
  fredsJamsLive: "https://fredpasqua.github.io/fredsjams_client_v2/",
  clientSampleLive: "https://fredpasqua.github.io/webpage-template/",
  clientSampleLink: "https://github.com/fredpasqua/webpage-template",
  route38Link: "https://www.route38dental.com",
};
